name: Deploy ASP.NET Core to Local IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop IIS
        run: C:\Windows\System32\iisreset.exe /stop

      - name: Clean Old Files
        run: |
          if (Test-Path "C:\inetpub\wwwroot\EmployeeAPI") {
              Remove-Item "C:\inetpub\wwwroot\EmployeeAPI\*" -Recurse -Force
          }

      - name: Publish App
        run: dotnet publish EmployeeApi.sln -c Release -o C:\inetpub\wwwroot\EmployeeAPI

      - name: Start IIS
        run: C:\Windows\System32\iisreset.exe /start
